Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "docker-netdeepdive"

  # Private network (optional, useful if you want to ssh from host easily)
  config.vm.network "private_network", ip: "192.168.56.77"

  # Resource tuning
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Week7-Docker-Networking"
    vb.memory = 3072
    vb.cpus = 2
  end

  # Sync project folder to VM
  config.vm.synced_folder ".", "/vagrant"

  # Provision
  config.vm.provision "shell", path: "provision.sh"
end