Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # VM 1: Jenkins
  config.vm.define "jenkins" do |j|
    j.vm.hostname = "jenkins"
    j.vm.network "private_network", ip: "192.168.56.110"
    j.vm.network "forwarded_port", guest: 8080, host: 8080
    j.vm.provider "virtualbox" do |vb|
      vb.name = "week7-jenkins"
      vb.memory = 3072
      vb.cpus = 2
    end
    j.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    j.vm.provision "shell", path: "provision.sh", args: ["jenkins"], privileged: true
  end

  # VM 2: Deploy target
  config.vm.define "deploy" do |d|
    d.vm.hostname = "deploy"
    d.vm.network "private_network", ip: "192.168.56.111"
    d.vm.network "forwarded_port", guest: 8081, host: 8081
    d.vm.provider "virtualbox" do |vb|
      vb.name = "week7-deploy"
      vb.memory = 2048
      vb.cpus = 2
    end
    d.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    d.vm.provision "shell", path: "provision.sh", args: ["deploy"], privileged: true
  end
end