Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  end

  # -----------------------------
  # VM 1: MongoDB (Ubuntu Xenial)
  # -----------------------------
  config.vm.define "mongo" do |m|
    m.vm.box = "ubuntu/xenial64"
    m.vm.hostname = "mongo-ubuntu"
    m.vm.network "private_network", ip: "192.168.56.10"
    m.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    m.vm.provision "shell", path: "scripts/ubuntu-mongo-3.2.5-rs0.sh"
  end

  # -----------------------------
  # VM 2: Redis (Ubuntu Xenial)
  # -----------------------------
  config.vm.define "redis" do |r|
    r.vm.box = "ubuntu/xenial64"
    r.vm.hostname = "redis-ubuntu"
    r.vm.network "private_network", ip: "192.168.56.11"
    r.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    r.vm.provision "shell", path: "scripts/ubuntu-redis-3.2.13.sh"
  end

  # -----------------------------
  # VM 3: RabbitMQ (Ubuntu Xenial)
  # -----------------------------
  config.vm.define "rabbitmq" do |q|
    q.vm.box = "ubuntu/xenial64"
    q.vm.hostname = "rabbitmq-ubuntu"
    q.vm.network "private_network", ip: "192.168.56.12"
    q.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    q.vm.provision "shell", path: "scripts/ubuntu-rabbitmq-cluster.sh"
  end
end
