Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "jenkins-ubuntu"

  config.vm.network "private_network", ip: "192.168.56.31"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
  config.vm.network "forwarded_port", guest: 3000, host: 3000, auto_correct: true

  config.vm.provider "virtualbox" do |vb|
    vb.name = "jenkins-ubuntu-2"
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "jenkins_provision.sh"
end